from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent

INPUT_VIDEO = PROJECT_ROOT / "input" / "test.mp4"
OUTPUT_VIDEO = PROJECT_ROOT / "output" / "tracked.mp4"
SAVE_OUTPUT_VIDEO = True
MODEL_PATH = PROJECT_ROOT / "models" / "yolo26n.pt"

AI_IMAGE_SIZE = 960
AI_CONFIDENCE = 0.05
TARGET_CLASSES = ["car", "truck", "bus", "motorcycle"]

CANDIDATE_MIN_CONF = 0.05
CANDIDATE_MAX_CONF = 0.25
CONFIRMED_CONF = 0.25
CANDIDATE_CONFIRM_CONF = 0.12
MAX_CANDIDATES = 6
CANDIDATE_IMG_SIZE = 320
CANDIDATE_CHECK_EVERY = 3
CANDIDATE_CONFIRM_CHECKS = 3
CANDIDATE_TIMEOUT = 5.0

TRACKER = "botsort"
TRACK_HIGH_THRESH = 0.05
TRACK_LOW_THRESH = 0.01
TRACK_NEW_THRESH = 0.05
GMC_METHOD = "sparseOptFlow"
REID_ENABLED = False
TRACK_BUFFER = 30

BOX_THICKNESS = 2
BOX_SMOOTHING = 0.70
SHOW_ID = True
SHOW_CONFIDENCE = True
SHOW_FPS = True
SHOW_CANDIDATES = True

WEB_HOST = "127.0.0.1"
WEB_PORT = 5000
